version: '3.8'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=rayann.folleas@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge



  vue:
    hostname: collectifae.com
    restart: always
    build: ./front
    depends_on: 
      - node
    ports:
      - 8080:80
    volumes:
      - ./:/back
    environment:
      - VIRTUAL_HOST=collectifae.com
      - LETSENCRYPT_HOST=collectifae.com
  database:
    image: mongo
    restart: always 
    ports:
      - 27018:27017
    volumes: 
      - my_data:/data/db 
  node:
    restart: always
    build: ./back
    depends_on: 
      - database
    ports:
      - 5000:5000
    volumes:
      - ./:/node-express-mongodb

volumes:
  my_data:
  conf:
  vhost:
  html:
  certs:
  acme: