version: '3.8'
services:
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - conf:/etc/nginx/conf.d
  #     - vhost:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
  #     - certs:/etc/nginx/certs:ro
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   network_mode: bridge

  # acme-companion:
  #   image: nginxproxy/acme-companion
  #   container_name: nginx-proxy-acme
  #   environment:
  #     - DEFAULT_EMAIL=rayann.folleas@gmail.com
  #     - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
  #   volumes_from:
  #     - nginx-proxy
  #   volumes:
  #     - certs:/etc/nginx/certs:rw
  #     - acme:/etc/acme.sh
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   network_mode: bridge



  react_native_app:
    build:
      context: ./front_def
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./react_native_app:/opt/react_native_app/app:delegated
      - ./react_native_app/package.json:/opt/react_native_app/package.json
      - ./react_native_app/package-lock.json:/opt/react_native_app/package-lock.json
      - notused:/opt/react_native_app/app/node_modules
    healthcheck:
      disable: true
  database:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - my_data:/data/db
  node:
    restart: always
    build: ./back
    depends_on:
      - database
    ports:
      - 5000:5000
    volumes:
      - ./:/node-express-mongodb

volumes:
  notused:
  my_data:
  conf:
  vhost:
  html:
  certs:
  acme:
