version: '3.8'
services:
  database:
    image: mongo
    restart: always 
    ports:
      - 27018:27017
    volumes: 
      - my_data:/data/db 
  node:
    restart: always
    build: ./back
    depends_on: 
      - database
    ports:
      - 5000:5000
    volumes:
      - ./:/node-express-mongodb
  vue:
    restart: always
    build: ./front
    depends_on: 
      - node
    ports:
      - 8080:80
    volumes:
      - ./:/back
volumes:
 my_data:
