version: '3.8'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs 
      - vhost:/etc/nginx/vhost.d 
      - html:/usr/share/nginx/html 
      - /var/run/docker.sock:/tmp/docker.sock:ro 
      - nginxproxy/nginx-proxy
    networks:
      - nginx
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - "DEFAULT_EMAIL=rayann.folleas@gmail.com"
    depends_on:
      - nginx-proxy


  vue:
    hostname: collectifae.com
    restart: always
    build: ./front
    depends_on: 
      - node
    ports:
      - 8080:80
    volumes:
      - ./:/back
    environment:
      - VIRTUAL_HOST=collectifae.com
      - LETSENCRYPT_HOST=collectifae.com
  database:
    image: mongo
    restart: always 
    ports:
      - 27018:27017
    volumes: 
      - my_data:/data/db 
  node:
    restart: always
    build: ./back
    depends_on: 
      - database
    ports:
      - 5000:5000
    volumes:
      - ./:/node-express-mongodb
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=collectifae.com
      - LETSENCRYPT_HOST=collectifae.com
      - LETSENCRYPT_TEST=true
    networks:
      - nginx


networks:
  nginx:

volumes:
  my_data:
  acme:
  html:
  vhost:
  conf:
  certs:
